// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/luckyAkbar/atec-api/internal/model (interfaces: SDTemplateUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	common "github.com/luckyAkbar/atec-api/internal/common"
	model "github.com/luckyAkbar/atec-api/internal/model"
)

// MockSDTemplateUsecase is a mock of SDTemplateUsecase interface.
type MockSDTemplateUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSDTemplateUsecaseMockRecorder
}

// MockSDTemplateUsecaseMockRecorder is the mock recorder for MockSDTemplateUsecase.
type MockSDTemplateUsecaseMockRecorder struct {
	mock *MockSDTemplateUsecase
}

// NewMockSDTemplateUsecase creates a new mock instance.
func NewMockSDTemplateUsecase(ctrl *gomock.Controller) *MockSDTemplateUsecase {
	mock := &MockSDTemplateUsecase{ctrl: ctrl}
	mock.recorder = &MockSDTemplateUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSDTemplateUsecase) EXPECT() *MockSDTemplateUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSDTemplateUsecase) Create(arg0 context.Context, arg1 *model.SDTemplate) (*model.GeneratedSDTemplate, *common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*model.GeneratedSDTemplate)
	ret1, _ := ret[1].(*common.Error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSDTemplateUsecaseMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSDTemplateUsecase)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockSDTemplateUsecase) Delete(arg0 context.Context, arg1 uuid.UUID) (*model.GeneratedSDTemplate, *common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*model.GeneratedSDTemplate)
	ret1, _ := ret[1].(*common.Error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSDTemplateUsecaseMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSDTemplateUsecase)(nil).Delete), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockSDTemplateUsecase) FindByID(arg0 context.Context, arg1 uuid.UUID) (*model.GeneratedSDTemplate, *common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.GeneratedSDTemplate)
	ret1, _ := ret[1].(*common.Error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSDTemplateUsecaseMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSDTemplateUsecase)(nil).FindByID), arg0, arg1)
}

// Search mocks base method.
func (m *MockSDTemplateUsecase) Search(arg0 context.Context, arg1 *model.SearchSDTemplateInput) (*model.SearchSDTemplateOutput, *common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1)
	ret0, _ := ret[0].(*model.SearchSDTemplateOutput)
	ret1, _ := ret[1].(*common.Error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSDTemplateUsecaseMockRecorder) Search(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSDTemplateUsecase)(nil).Search), arg0, arg1)
}

// Update mocks base method.
func (m *MockSDTemplateUsecase) Update(arg0 context.Context, arg1 uuid.UUID, arg2 *model.SDTemplate) (*model.GeneratedSDTemplate, *common.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.GeneratedSDTemplate)
	ret1, _ := ret[1].(*common.Error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSDTemplateUsecaseMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSDTemplateUsecase)(nil).Update), arg0, arg1, arg2)
}
